---
language: python
python:
  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
  - ANSIBLE_VERSION=2.4.1.0
cache: bundler
#sudo: false
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
#  - sudo pip install --no-use-wheel https://github.com/ansible/ansible/archive/devel.zip
  - sudo pip install ansible==$ANSIBLE_VERSION
script:
  - ansible --version
#  - export ANSIBLE_ROLES_PATH="../"
#  - echo localhost > inventory
  - ansible-playbook -i hosts --syntax-check supervisor.yml
  - ansible-playbook -i hosts --connection=local --sudo -vvvv supervisor.yml
